# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NewEmployee(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, attr=None):  # noqa: E501
        """NewEmployee - a model defined in OpenAPI

        :param name: The name of this NewEmployee.  # noqa: E501
        :type name: str
        :param attr: The attr of this NewEmployee.  # noqa: E501
        :type attr: str
        """
        self.openapi_types = {
            'name': str,
            'attr': str
        }

        self.attribute_map = {
            'name': 'name',
            'attr': 'attr'
        }

        self._name = name
        self._attr = attr

    @classmethod
    def from_dict(cls, dikt) -> 'NewEmployee':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewEmployee of this NewEmployee.  # noqa: E501
        :rtype: NewEmployee
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this NewEmployee.


        :return: The name of this NewEmployee.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NewEmployee.


        :param name: The name of this NewEmployee.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def attr(self):
        """Gets the attr of this NewEmployee.


        :return: The attr of this NewEmployee.
        :rtype: str
        """
        return self._attr

    @attr.setter
    def attr(self, attr):
        """Sets the attr of this NewEmployee.


        :param attr: The attr of this NewEmployee.
        :type attr: str
        """

        self._attr = attr
